program: run.py
method: random
metric:
  goal: maximize
  name: Average Precision
parameters:
  batch_size: 
    distribution: int_uniform
    min: 4
    max: 19
  img_size: 
    value: 512
  backbone:
    value: efficientdet_d0
  max_epochs:
    value: 150
  lr: 
    values: [0.05, 0.01, 0.005, 0.001, 0.0005, 0.0001, 0.00005, 0.00001]
  iou_thres: 
    distribution: normal
    mu: 0.6
    sigma: 0.2
  optimizer:
    values: ['AdamW', 'SGD', 'Adam']
command:
  - ${env}
  - python3
  - ${program}

project: EfficientDetD0 Sweep (Random)
name: EfficientDet D0 Initial Sweep (no confidence level)